from __future__ import annotations

from sqlalchemy import (
    JSON,
    BigInteger,
    Column,
    DateTime,
    Integer,
    MetaData,
    Numeric,
    String,
    Table,
    Text,
    UniqueConstraint,
)


NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}
metadata = MetaData(naming_convention=NAMING_CONVENTION)

ledger_events = Table(
    "ledger_events",
    metadata,
    Column("sequence", Integer, primary_key=True, autoincrement=True),
    Column("event_id", String(36), nullable=False, unique=True),
    Column("event_type", String(120), nullable=False, index=True),
    Column("event_time", DateTime(timezone=True), nullable=False),
    Column("emitted_at", DateTime(timezone=True), nullable=False),
    Column("producer", String(80), nullable=False),
    Column("correlation_id", String(36), nullable=False, index=True),
    Column("causation_id", String(36), nullable=True),
    Column("schema_version", Integer, nullable=False),
    Column("payload", JSON, nullable=False),
)

raw_objects = Table(
    "raw_objects",
    metadata,
    Column("raw_object_id", String(36), primary_key=True),
    Column("provider", String(40), nullable=False),
    Column("data_type", String(80), nullable=False),
    Column("content_sha256", String(64), nullable=False),
    Column("uri", Text, nullable=False),
    Column("payload_bytes", BigInteger, nullable=False),
    Column("provider_received_at", DateTime(timezone=True), nullable=True),
    Column("ingested_at", DateTime(timezone=True), nullable=False),
    Column("request_metadata", JSON, nullable=False),
    UniqueConstraint("provider", "content_sha256", name="uq_raw_objects_provider_sha256"),
)

market_bars = Table(
    "market_bars",
    metadata,
    Column("bar_id", String(36), primary_key=True),
    Column("symbol", String(24), nullable=False, index=True),
    Column("timeframe", String(16), nullable=False),
    Column("event_time", DateTime(timezone=True), nullable=False, index=True),
    Column("available_from", DateTime(timezone=True), nullable=False),
    Column("open", Numeric(20, 8), nullable=False),
    Column("high", Numeric(20, 8), nullable=False),
    Column("low", Numeric(20, 8), nullable=False),
    Column("close", Numeric(20, 8), nullable=False),
    Column("volume", BigInteger, nullable=False),
    Column("trade_count", BigInteger, nullable=True),
    Column("vwap", Numeric(20, 8), nullable=True),
    Column("source", String(40), nullable=False),
    Column("feed", String(20), nullable=False),
    Column("raw_object_id", String(36), nullable=False),
    Column("ingested_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint(
        "symbol",
        "timeframe",
        "event_time",
        "source",
        "feed",
        name="uq_market_bars_identity",
    ),
)

market_trades = Table(
    "market_trades",
    metadata,
    Column("trade_id", String(36), primary_key=True),
    Column("provider_trade_id", String(80), nullable=False),
    Column("symbol", String(24), nullable=False, index=True),
    Column("event_time", DateTime(timezone=True), nullable=False, index=True),
    Column("available_from", DateTime(timezone=True), nullable=False),
    Column("price", Numeric(20, 8), nullable=False),
    Column("size", BigInteger, nullable=False),
    Column("exchange", String(20), nullable=False),
    Column("conditions", JSON, nullable=False),
    Column("tape", String(8), nullable=True),
    Column("source", String(40), nullable=False),
    Column("feed", String(20), nullable=False),
    Column("raw_object_id", String(36), nullable=False),
    Column("ingested_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint(
        "source",
        "feed",
        "symbol",
        "provider_trade_id",
        name="uq_market_trades_provider_identity",
    ),
)

market_quotes = Table(
    "market_quotes",
    metadata,
    Column("quote_id", String(36), primary_key=True),
    Column("quote_fingerprint", String(64), nullable=False),
    Column("symbol", String(24), nullable=False, index=True),
    Column("event_time", DateTime(timezone=True), nullable=False, index=True),
    Column("available_from", DateTime(timezone=True), nullable=False),
    Column("bid_exchange", String(20), nullable=False),
    Column("bid_price", Numeric(20, 8), nullable=False),
    Column("bid_size", BigInteger, nullable=False),
    Column("ask_exchange", String(20), nullable=False),
    Column("ask_price", Numeric(20, 8), nullable=False),
    Column("ask_size", BigInteger, nullable=False),
    Column("conditions", JSON, nullable=False),
    Column("tape", String(8), nullable=True),
    Column("source", String(40), nullable=False),
    Column("feed", String(20), nullable=False),
    Column("raw_object_id", String(36), nullable=False),
    Column("ingested_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint(
        "source",
        "feed",
        "quote_fingerprint",
        name="uq_market_quotes_provider_identity",
    ),
)

option_snapshots = Table(
    "option_snapshots",
    metadata,
    Column("option_snapshot_id", String(36), primary_key=True),
    Column("contract_symbol", String(32), nullable=False, index=True),
    Column("underlying_symbol", String(24), nullable=False, index=True),
    Column("as_of", DateTime(timezone=True), nullable=False, index=True),
    Column("available_from", DateTime(timezone=True), nullable=False),
    Column("bid_price", Numeric(20, 8), nullable=True),
    Column("bid_size", BigInteger, nullable=True),
    Column("ask_price", Numeric(20, 8), nullable=True),
    Column("ask_size", BigInteger, nullable=True),
    Column("last_trade_price", Numeric(20, 8), nullable=True),
    Column("last_trade_size", BigInteger, nullable=True),
    Column("implied_volatility", Numeric(20, 10), nullable=True),
    Column("delta", Numeric(20, 10), nullable=True),
    Column("gamma", Numeric(20, 10), nullable=True),
    Column("theta", Numeric(20, 10), nullable=True),
    Column("vega", Numeric(20, 10), nullable=True),
    Column("rho", Numeric(20, 10), nullable=True),
    Column("source", String(40), nullable=False),
    Column("feed", String(20), nullable=False),
    Column("raw_object_id", String(36), nullable=False),
    Column("ingested_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint(
        "source",
        "feed",
        "contract_symbol",
        "as_of",
        name="uq_option_snapshots_identity",
    ),
)

ingestion_runs = Table(
    "ingestion_runs",
    metadata,
    Column("ingestion_run_id", String(36), primary_key=True),
    Column("provider", String(40), nullable=False),
    Column("data_type", String(80), nullable=False),
    Column("status", String(24), nullable=False),
    Column("requested_at", DateTime(timezone=True), nullable=False),
    Column("completed_at", DateTime(timezone=True), nullable=True),
    Column("request_metadata", JSON, nullable=False),
    Column("pages_received", Integer, nullable=False, default=0),
    Column("records_received", Integer, nullable=False, default=0),
    Column("records_inserted", Integer, nullable=False, default=0),
    Column("error_code", String(80), nullable=True),
)
