from __future__ import annotations

from sqlalchemy import (
    JSON,
    BigInteger,
    Boolean,
    Column,
    DateTime,
    Integer,
    MetaData,
    Numeric,
    String,
    Table,
    Text,
    UniqueConstraint,
    ForeignKey,
)


NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}
metadata = MetaData(naming_convention=NAMING_CONVENTION)

ledger_events = Table(
    "ledger_events",
    metadata,
    Column("sequence", Integer, primary_key=True, autoincrement=True),
    Column("event_id", String(36), nullable=False, unique=True),
    Column("event_type", String(120), nullable=False, index=True),
    Column("event_time", DateTime(timezone=True), nullable=False),
    Column("emitted_at", DateTime(timezone=True), nullable=False),
    Column("producer", String(80), nullable=False),
    Column("correlation_id", String(36), nullable=False, index=True),
    Column("causation_id", String(36), nullable=True),
    Column("schema_version", Integer, nullable=False),
    Column("payload", JSON, nullable=False),
)

raw_objects = Table(
    "raw_objects",
    metadata,
    Column("raw_object_id", String(36), primary_key=True),
    Column("provider", String(40), nullable=False),
    Column("data_type", String(80), nullable=False),
    Column("content_sha256", String(64), nullable=False),
    Column("uri", Text, nullable=False),
    Column("payload_bytes", BigInteger, nullable=False),
    Column("provider_received_at", DateTime(timezone=True), nullable=True),
    Column("ingested_at", DateTime(timezone=True), nullable=False),
    Column("request_metadata", JSON, nullable=False),
    UniqueConstraint("provider", "content_sha256", name="uq_raw_objects_provider_sha256"),
)

market_bars = Table(
    "market_bars",
    metadata,
    Column("bar_id", String(36), primary_key=True),
    Column("symbol", String(24), nullable=False, index=True),
    Column("timeframe", String(16), nullable=False),
    Column("event_time", DateTime(timezone=True), nullable=False, index=True),
    Column("available_from", DateTime(timezone=True), nullable=False),
    Column("open", Numeric(20, 8), nullable=False),
    Column("high", Numeric(20, 8), nullable=False),
    Column("low", Numeric(20, 8), nullable=False),
    Column("close", Numeric(20, 8), nullable=False),
    Column("volume", BigInteger, nullable=False),
    Column("trade_count", BigInteger, nullable=True),
    Column("vwap", Numeric(20, 8), nullable=True),
    Column("source", String(40), nullable=False),
    Column("feed", String(20), nullable=False),
    Column("raw_object_id", String(36), nullable=False),
    Column("ingested_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint(
        "symbol",
        "timeframe",
        "event_time",
        "source",
        "feed",
        name="uq_market_bars_identity",
    ),
)

market_trades = Table(
    "market_trades",
    metadata,
    Column("trade_id", String(36), primary_key=True),
    Column("provider_trade_id", String(80), nullable=False),
    Column("symbol", String(24), nullable=False, index=True),
    Column("event_time", DateTime(timezone=True), nullable=False, index=True),
    Column("available_from", DateTime(timezone=True), nullable=False),
    Column("price", Numeric(20, 8), nullable=False),
    Column("size", BigInteger, nullable=False),
    Column("exchange", String(20), nullable=False),
    Column("conditions", JSON, nullable=False),
    Column("tape", String(8), nullable=True),
    Column("source", String(40), nullable=False),
    Column("feed", String(20), nullable=False),
    Column("raw_object_id", String(36), nullable=False),
    Column("ingested_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint(
        "source",
        "feed",
        "symbol",
        "provider_trade_id",
        name="uq_market_trades_provider_identity",
    ),
)

market_quotes = Table(
    "market_quotes",
    metadata,
    Column("quote_id", String(36), primary_key=True),
    Column("quote_fingerprint", String(64), nullable=False),
    Column("symbol", String(24), nullable=False, index=True),
    Column("event_time", DateTime(timezone=True), nullable=False, index=True),
    Column("available_from", DateTime(timezone=True), nullable=False),
    Column("bid_exchange", String(20), nullable=False),
    Column("bid_price", Numeric(20, 8), nullable=False),
    Column("bid_size", BigInteger, nullable=False),
    Column("ask_exchange", String(20), nullable=False),
    Column("ask_price", Numeric(20, 8), nullable=False),
    Column("ask_size", BigInteger, nullable=False),
    Column("conditions", JSON, nullable=False),
    Column("tape", String(8), nullable=True),
    Column("source", String(40), nullable=False),
    Column("feed", String(20), nullable=False),
    Column("raw_object_id", String(36), nullable=False),
    Column("ingested_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint(
        "source",
        "feed",
        "quote_fingerprint",
        name="uq_market_quotes_provider_identity",
    ),
)

option_snapshots = Table(
    "option_snapshots",
    metadata,
    Column("option_snapshot_id", String(36), primary_key=True),
    Column("contract_symbol", String(32), nullable=False, index=True),
    Column("underlying_symbol", String(24), nullable=False, index=True),
    Column("as_of", DateTime(timezone=True), nullable=False, index=True),
    Column("available_from", DateTime(timezone=True), nullable=False),
    Column("bid_price", Numeric(20, 8), nullable=True),
    Column("bid_size", BigInteger, nullable=True),
    Column("ask_price", Numeric(20, 8), nullable=True),
    Column("ask_size", BigInteger, nullable=True),
    Column("last_trade_price", Numeric(20, 8), nullable=True),
    Column("last_trade_size", BigInteger, nullable=True),
    Column("implied_volatility", Numeric(20, 10), nullable=True),
    Column("delta", Numeric(20, 10), nullable=True),
    Column("gamma", Numeric(20, 10), nullable=True),
    Column("theta", Numeric(20, 10), nullable=True),
    Column("vega", Numeric(20, 10), nullable=True),
    Column("rho", Numeric(20, 10), nullable=True),
    Column("source", String(40), nullable=False),
    Column("feed", String(20), nullable=False),
    Column("raw_object_id", String(36), nullable=False),
    Column("ingested_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint(
        "source",
        "feed",
        "contract_symbol",
        "as_of",
        name="uq_option_snapshots_identity",
    ),
)

ingestion_runs = Table(
    "ingestion_runs",
    metadata,
    Column("ingestion_run_id", String(36), primary_key=True),
    Column("provider", String(40), nullable=False),
    Column("data_type", String(80), nullable=False),
    Column("status", String(24), nullable=False),
    Column("requested_at", DateTime(timezone=True), nullable=False),
    Column("completed_at", DateTime(timezone=True), nullable=True),
    Column("request_metadata", JSON, nullable=False),
    Column("pages_received", Integer, nullable=False, default=0),
    Column("records_received", Integer, nullable=False, default=0),
    Column("records_inserted", Integer, nullable=False, default=0),
    Column("error_code", String(80), nullable=True),
)

entities = Table(
    "entities",
    metadata,
    Column("entity_id", String(36), primary_key=True),
    Column("primary_symbol", String(24), nullable=False, index=True),
    Column("canonical_name", Text, nullable=True),
    Column("cik", String(10), nullable=True, index=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint("primary_symbol", name="uq_entities_primary_symbol"),
    UniqueConstraint("cik", name="uq_entities_cik"),
)

entity_symbols = Table(
    "entity_symbols",
    metadata,
    Column(
        "entity_id",
        String(36),
        ForeignKey("entities.entity_id", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column("symbol", String(24), primary_key=True, index=True),
)

source_documents = Table(
    "source_documents",
    metadata,
    Column("document_id", String(36), primary_key=True),
    Column("provider", String(40), nullable=False),
    Column("provider_document_id", String(160), nullable=False),
    Column("canonical_url", Text, nullable=False),
    Column("source_kind", String(40), nullable=False, index=True),
    Column("source_tier", String(16), nullable=False, index=True),
    Column("publisher", Text, nullable=False),
    Column("published_at", DateTime(timezone=True), nullable=False, index=True),
    Column("first_seen_at", DateTime(timezone=True), nullable=False),
    Column("last_seen_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint(
        "provider",
        "provider_document_id",
        name="uq_source_documents_provider_identity",
    ),
)

source_document_versions = Table(
    "source_document_versions",
    metadata,
    Column("version_id", String(36), primary_key=True),
    Column(
        "document_id",
        String(36),
        ForeignKey("source_documents.document_id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    ),
    Column("content_sha256", String(64), nullable=False),
    Column("title", Text, nullable=False),
    Column("summary", Text, nullable=True),
    Column("body_text", Text, nullable=True),
    Column("corrected_at", DateTime(timezone=True), nullable=True),
    Column("ingested_at", DateTime(timezone=True), nullable=False, index=True),
    Column("raw_object_id", String(36), nullable=False),
    UniqueConstraint(
        "document_id",
        "content_sha256",
        name="uq_source_document_versions_content",
    ),
)

document_entities = Table(
    "document_entities",
    metadata,
    Column(
        "document_id",
        String(36),
        ForeignKey("source_documents.document_id", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "entity_id",
        String(36),
        ForeignKey("entities.entity_id", ondelete="CASCADE"),
        primary_key=True,
    ),
)

document_symbols = Table(
    "document_symbols",
    metadata,
    Column(
        "document_id",
        String(36),
        ForeignKey("source_documents.document_id", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column("symbol", String(24), primary_key=True, index=True),
)

catalysts = Table(
    "catalysts",
    metadata,
    Column("catalyst_id", String(36), primary_key=True),
    Column("canonical_key", String(64), nullable=False, unique=True),
    Column("catalyst_type", String(40), nullable=False, index=True),
    Column("primary_symbol", String(24), nullable=False, index=True),
    Column("event_time", DateTime(timezone=True), nullable=False, index=True),
    Column("available_from", DateTime(timezone=True), nullable=False),
    Column("last_updated_at", DateTime(timezone=True), nullable=False),
    Column("headline", Text, nullable=False),
    Column("primary_source_document_id", String(36), nullable=True),
    Column("status", String(24), nullable=False),
    Column("source_count", Integer, nullable=False),
)

catalyst_documents = Table(
    "catalyst_documents",
    metadata,
    Column(
        "catalyst_id",
        String(36),
        ForeignKey("catalysts.catalyst_id", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "document_id",
        String(36),
        ForeignKey("source_documents.document_id", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column("match_method", String(40), nullable=False),
    Column("match_score", Numeric(8, 6), nullable=False),
    Column("linked_at", DateTime(timezone=True), nullable=False),
)

corporate_facts = Table(
    "corporate_facts",
    metadata,
    Column("fact_id", String(36), primary_key=True),
    Column("fact_fingerprint", String(64), nullable=False, unique=True),
    Column("entity_id", String(36), nullable=True, index=True),
    Column("symbol", String(24), nullable=False, index=True),
    Column("cik", String(10), nullable=False, index=True),
    Column("issuer_name", Text, nullable=False),
    Column("taxonomy", String(80), nullable=False),
    Column("tag", String(160), nullable=False, index=True),
    Column("unit", String(40), nullable=False),
    Column("period_start", DateTime(timezone=True), nullable=True),
    Column("period_end", DateTime(timezone=True), nullable=False),
    Column("filed_at", DateTime(timezone=True), nullable=False, index=True),
    Column("accepted_at", DateTime(timezone=True), nullable=True),
    Column("fiscal_year", Integer, nullable=True),
    Column("fiscal_period", String(20), nullable=True),
    Column("form", String(20), nullable=False),
    Column("accession_number", String(32), nullable=True),
    Column("numeric_value", Numeric(30, 10), nullable=True),
    Column("value_text", Text, nullable=False),
    Column("available_from", DateTime(timezone=True), nullable=False),
    Column("raw_object_id", String(36), nullable=False),
    Column("ingested_at", DateTime(timezone=True), nullable=False),
)

corporate_actions = Table(
    "corporate_actions",
    metadata,
    Column("corporate_action_id", String(36), primary_key=True),
    Column("action_fingerprint", String(64), nullable=False, unique=True),
    Column("symbol", String(24), nullable=False, index=True),
    Column("action_type", String(32), nullable=False, index=True),
    Column("effective_at", DateTime(timezone=True), nullable=False, index=True),
    Column("available_from", DateTime(timezone=True), nullable=False, index=True),
    Column("split_ratio", Numeric(24, 10), nullable=True),
    Column("cash_amount", Numeric(24, 10), nullable=True),
    Column("currency", String(8), nullable=True),
    Column("new_symbol", String(24), nullable=True),
    Column("source", String(40), nullable=False),
    Column("raw_object_id", String(36), nullable=False),
    Column("ingested_at", DateTime(timezone=True), nullable=False),
)

universe_memberships = Table(
    "universe_memberships",
    metadata,
    Column("membership_id", String(36), primary_key=True),
    Column("universe", String(80), nullable=False, index=True),
    Column("symbol", String(24), nullable=False, index=True),
    Column("effective_from", DateTime(timezone=True), nullable=False, index=True),
    Column("effective_to", DateTime(timezone=True), nullable=True),
    Column("available_from", DateTime(timezone=True), nullable=False),
    Column("source", String(40), nullable=False),
    Column("source_version", String(80), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint(
        "universe",
        "symbol",
        "effective_from",
        "source",
        "source_version",
        name="uq_universe_memberships_identity",
    ),
)

evidence_packets = Table(
    "evidence_packets",
    metadata,
    Column("evidence_packet_id", String(36), primary_key=True),
    Column("symbol", String(24), nullable=False, index=True),
    Column("as_of", DateTime(timezone=True), nullable=False, index=True),
    Column("evidence_hash", String(64), nullable=False),
    Column("references_json", JSON, nullable=False),
    Column("source_max_available_from", DateTime(timezone=True), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint(
        "symbol",
        "as_of",
        "evidence_hash",
        name="uq_evidence_packets_identity",
    ),
)

feature_snapshots = Table(
    "feature_snapshots",
    metadata,
    Column("feature_snapshot_id", String(36), primary_key=True),
    Column(
        "evidence_packet_id",
        String(36),
        ForeignKey("evidence_packets.evidence_packet_id"),
        nullable=False,
        index=True,
    ),
    Column("symbol", String(24), nullable=False, index=True),
    Column("timeframe", String(16), nullable=False),
    Column("as_of", DateTime(timezone=True), nullable=False, index=True),
    Column("feature_set_version", String(80), nullable=False),
    Column("feature_values", JSON, nullable=False),
    Column("source_max_available_from", DateTime(timezone=True), nullable=False),
    Column("data_hash", String(64), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint(
        "symbol",
        "timeframe",
        "as_of",
        "feature_set_version",
        "data_hash",
        name="uq_feature_snapshots_identity",
    ),
)

strategy_specs = Table(
    "strategy_specs",
    metadata,
    Column("strategy_spec_id", String(36), primary_key=True),
    Column("name", String(120), nullable=False),
    Column("version", String(120), nullable=False),
    Column("strategy_type", String(80), nullable=False),
    Column("timeframe", String(16), nullable=False),
    Column("feature_set_version", String(80), nullable=False),
    Column("parameters_json", JSON, nullable=False),
    Column("data_requirements_json", JSON, nullable=False),
    Column("code_sha256", String(64), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint("name", "version", name="uq_strategy_specs_name_version"),
)

experiment_runs = Table(
    "experiment_runs",
    metadata,
    Column("experiment_run_id", String(36), primary_key=True),
    Column(
        "strategy_spec_id",
        String(36),
        ForeignKey("strategy_specs.strategy_spec_id"),
        nullable=False,
        index=True,
    ),
    Column("symbol", String(24), nullable=False, index=True),
    Column("timeframe", String(16), nullable=False),
    Column("as_of_start", DateTime(timezone=True), nullable=False),
    Column("as_of_end", DateTime(timezone=True), nullable=False),
    Column("dataset_hash", String(64), nullable=False, index=True),
    Column("code_git_sha", String(64), nullable=False),
    Column("status", String(24), nullable=False, index=True),
    Column("cost_model_json", JSON, nullable=False),
    Column("metrics_json", JSON, nullable=False),
    Column("feature_snapshot_ids", JSON, nullable=False),
    Column("started_at", DateTime(timezone=True), nullable=False),
    Column("finished_at", DateTime(timezone=True), nullable=False),
)

backtest_trades = Table(
    "backtest_trades",
    metadata,
    Column("trade_id", String(36), primary_key=True),
    Column(
        "experiment_run_id",
        String(36),
        ForeignKey(
            "experiment_runs.experiment_run_id",
            name="fk_bt_events_experiment",
            ondelete="CASCADE",
        ),
        nullable=False,
        index=True,
    ),
    Column("symbol", String(24), nullable=False, index=True),
    Column("action", String(16), nullable=False),
    Column("signal_as_of", DateTime(timezone=True), nullable=False),
    Column("entry_time", DateTime(timezone=True), nullable=False),
    Column("exit_time", DateTime(timezone=True), nullable=False),
    Column("quantity", BigInteger, nullable=False),
    Column("exit_quantity", Numeric(24, 10), nullable=True),
    Column("entry_price", Numeric(20, 8), nullable=False),
    Column("exit_price", Numeric(20, 8), nullable=False),
    Column("gross_pnl", Numeric(24, 8), nullable=False),
    Column("corporate_action_cash", Numeric(24, 8), nullable=False, default=0),
    Column("transaction_cost", Numeric(24, 8), nullable=False),
    Column("net_pnl", Numeric(24, 8), nullable=False),
    Column(
        "feature_snapshot_id",
        String(36),
        ForeignKey("feature_snapshots.feature_snapshot_id"),
        nullable=False,
    ),
    Column("exit_reason", String(80), nullable=False),
)

backtest_portfolio_events = Table(
    "backtest_portfolio_events",
    metadata,
    Column("portfolio_event_id", String(36), primary_key=True),
    Column(
        "experiment_run_id",
        String(36),
        ForeignKey("experiment_runs.experiment_run_id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    ),
    Column("sequence", Integer, nullable=False),
    Column("event_type", String(32), nullable=False, index=True),
    Column("event_time", DateTime(timezone=True), nullable=False, index=True),
    Column("symbol", String(24), nullable=False, index=True),
    Column("cash_balance", Numeric(24, 8), nullable=False),
    Column("position_quantity", Numeric(24, 10), nullable=False),
    Column("cash_delta", Numeric(24, 8), nullable=False),
    Column("quantity_delta", Numeric(24, 10), nullable=False),
    Column("price", Numeric(20, 8), nullable=True),
    Column(
        "corporate_action_id",
        String(36),
        ForeignKey(
            "corporate_actions.corporate_action_id",
            name="fk_bt_events_action",
        ),
        nullable=True,
    ),
    Column(
        "feature_snapshot_id",
        String(36),
        ForeignKey(
            "feature_snapshots.feature_snapshot_id",
            name="fk_bt_events_feature",
        ),
        nullable=True,
    ),
    Column("details_json", JSON, nullable=False),
    UniqueConstraint(
        "experiment_run_id",
        "sequence",
        name="uq_backtest_portfolio_events_sequence",
    ),
)

feature_parity_checks = Table(
    "feature_parity_checks",
    metadata,
    Column("parity_check_id", String(36), primary_key=True),
    Column("symbol", String(24), nullable=False, index=True),
    Column("timeframe", String(16), nullable=False),
    Column("as_of", DateTime(timezone=True), nullable=False, index=True),
    Column("feature_set_version", String(80), nullable=False),
    Column("offline_data_hash", String(64), nullable=False),
    Column("online_data_hash", String(64), nullable=False),
    Column("matched", Boolean, nullable=False),
    Column("checked_at", DateTime(timezone=True), nullable=False),
)

validation_reports = Table(
    "validation_reports",
    metadata,
    Column("validation_report_id", String(36), primary_key=True),
    Column("symbol", String(24), nullable=False, index=True),
    Column("timeframe", String(16), nullable=False),
    Column("strategy_types", JSON, nullable=False),
    Column("selection_metric", String(40), nullable=False),
    Column("train_bars", Integer, nullable=False),
    Column("test_bars", Integer, nullable=False),
    Column("step_bars", Integer, nullable=False),
    Column("embargo_bars", Integer, nullable=False),
    Column("aggregate_metrics", JSON, nullable=False),
    Column("regime_metrics", JSON, nullable=False),
    Column("report_hash", String(64), nullable=False, index=True),
    Column("code_git_sha", String(64), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False, index=True),
)

validation_folds = Table(
    "validation_folds",
    metadata,
    Column("validation_fold_id", String(36), primary_key=True),
    Column(
        "validation_report_id",
        String(36),
        ForeignKey(
            "validation_reports.validation_report_id",
            name="fk_validation_folds_report",
            ondelete="CASCADE",
        ),
        nullable=False,
        index=True,
    ),
    Column("fold_number", Integer, nullable=False),
    Column("train_start", DateTime(timezone=True), nullable=False),
    Column("train_end", DateTime(timezone=True), nullable=False),
    Column("test_start", DateTime(timezone=True), nullable=False),
    Column("test_end", DateTime(timezone=True), nullable=False),
    Column("selected_strategy", String(80), nullable=False),
    Column("selection_metric", String(40), nullable=False),
    Column("train_experiment_ids", JSON, nullable=False),
    Column("test_experiment_ids", JSON, nullable=False),
    Column("selected_train_metrics", JSON, nullable=False),
    Column("selected_test_metrics", JSON, nullable=False),
    Column("selected_test_rank", Integer, nullable=False),
    Column("regime", String(24), nullable=False, index=True),
    UniqueConstraint(
        "validation_report_id",
        "fold_number",
        name="uq_validation_folds_report_number",
    ),
)

llm_invocations = Table(
    "llm_invocations",
    metadata,
    Column("invocation_id", String(36), primary_key=True),
    Column("workload", String(80), nullable=False, index=True),
    Column("routing_version", String(80), nullable=False),
    Column("routing_sha256", String(64), nullable=False),
    Column("code_git_sha", String(64), nullable=False),
    Column("provider", String(40), nullable=False, index=True),
    Column("model", String(120), nullable=False, index=True),
    Column("reasoning_effort", String(24), nullable=False),
    Column("prompt_version", String(120), nullable=False),
    Column("request_sha256", String(64), nullable=False, index=True),
    Column("input_sha256", String(64), nullable=False),
    Column("response_id", String(160), nullable=True),
    Column("output_text", Text, nullable=True),
    Column("output_sha256", String(64), nullable=True),
    Column("usage_json", JSON, nullable=False),
    Column("latency_ms", Integer, nullable=False),
    Column("status", String(24), nullable=False, index=True),
    Column("error_code", String(120), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False, index=True),
    Column("completed_at", DateTime(timezone=True), nullable=False),
)

llm_routing_revisions = Table(
    "llm_routing_revisions",
    metadata,
    Column("routing_revision_id", String(36), primary_key=True),
    Column("base_routing_version", String(80), nullable=False),
    Column("base_routing_sha256", String(64), nullable=False, index=True),
    Column("routing_version", String(120), nullable=False, unique=True),
    Column("routing_sha256", String(64), nullable=False),
    Column("routes_json", JSON, nullable=False),
    Column("reason", Text, nullable=False),
    Column("created_by", String(80), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False, index=True),
)
