from __future__ import annotations

from sqlalchemy import (
    JSON,
    BigInteger,
    Boolean,
    Column,
    DateTime,
    Integer,
    MetaData,
    Numeric,
    String,
    Table,
    Text,
    UniqueConstraint,
    ForeignKey,
)


NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}
metadata = MetaData(naming_convention=NAMING_CONVENTION)

ledger_events = Table(
    "ledger_events",
    metadata,
    Column("sequence", Integer, primary_key=True, autoincrement=True),
    Column("event_id", String(36), nullable=False),
    Column("event_type", String(120), nullable=False, index=True),
    Column("event_time", DateTime(timezone=True), nullable=False),
    Column("emitted_at", DateTime(timezone=True), nullable=False),
    Column("producer", String(80), nullable=False),
    Column("correlation_id", String(36), nullable=False, index=True),
    Column("causation_id", String(36), nullable=True),
    Column("schema_version", Integer, nullable=False),
    Column("payload", JSON, nullable=False),
    UniqueConstraint("event_id", name="uq_ledger_events_event_id"),
)

event_outbox = Table(
    "event_outbox",
    metadata,
    Column(
        "event_id",
        String(36),
        ForeignKey("ledger_events.event_id", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column("event_type", String(120), nullable=False, index=True),
    Column("envelope_json", Text, nullable=False),
    Column("status", String(24), nullable=False, index=True),
    Column("attempt_count", Integer, nullable=False),
    Column("lease_owner", String(120), nullable=True, index=True),
    Column("lease_expires_at", DateTime(timezone=True), nullable=True, index=True),
    Column("next_attempt_at", DateTime(timezone=True), nullable=False, index=True),
    Column("last_error", String(240), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Column("published_at", DateTime(timezone=True), nullable=True),
)

raw_objects = Table(
    "raw_objects",
    metadata,
    Column("raw_object_id", String(36), primary_key=True),
    Column("provider", String(40), nullable=False),
    Column("data_type", String(80), nullable=False),
    Column("content_sha256", String(64), nullable=False),
    Column("uri", Text, nullable=False),
    Column("payload_bytes", BigInteger, nullable=False),
    Column("provider_received_at", DateTime(timezone=True), nullable=True),
    Column("ingested_at", DateTime(timezone=True), nullable=False),
    Column("request_metadata", JSON, nullable=False),
    UniqueConstraint("provider", "content_sha256", name="uq_raw_objects_provider_sha256"),
)

market_bars = Table(
    "market_bars",
    metadata,
    Column("bar_id", String(36), primary_key=True),
    Column("symbol", String(24), nullable=False, index=True),
    Column("timeframe", String(16), nullable=False),
    Column("event_time", DateTime(timezone=True), nullable=False, index=True),
    Column("available_from", DateTime(timezone=True), nullable=False),
    Column("open", Numeric(20, 8), nullable=False),
    Column("high", Numeric(20, 8), nullable=False),
    Column("low", Numeric(20, 8), nullable=False),
    Column("close", Numeric(20, 8), nullable=False),
    Column("volume", BigInteger, nullable=False),
    Column("trade_count", BigInteger, nullable=True),
    Column("vwap", Numeric(20, 8), nullable=True),
    Column("source", String(40), nullable=False),
    Column("feed", String(20), nullable=False),
    Column("raw_object_id", String(36), nullable=False),
    Column("ingested_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint(
        "symbol",
        "timeframe",
        "event_time",
        "source",
        "feed",
        name="uq_market_bars_identity",
    ),
)

market_trades = Table(
    "market_trades",
    metadata,
    Column("trade_id", String(36), primary_key=True),
    Column("provider_trade_id", String(80), nullable=False),
    Column("symbol", String(24), nullable=False, index=True),
    Column("event_time", DateTime(timezone=True), nullable=False, index=True),
    Column("available_from", DateTime(timezone=True), nullable=False),
    Column("price", Numeric(20, 8), nullable=False),
    Column("size", BigInteger, nullable=False),
    Column("exchange", String(20), nullable=False),
    Column("conditions", JSON, nullable=False),
    Column("tape", String(8), nullable=True),
    Column("source", String(40), nullable=False),
    Column("feed", String(20), nullable=False),
    Column("raw_object_id", String(36), nullable=False),
    Column("ingested_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint(
        "source",
        "feed",
        "symbol",
        "provider_trade_id",
        name="uq_market_trades_provider_identity",
    ),
)

market_quotes = Table(
    "market_quotes",
    metadata,
    Column("quote_id", String(36), primary_key=True),
    Column("quote_fingerprint", String(64), nullable=False),
    Column("symbol", String(24), nullable=False, index=True),
    Column("event_time", DateTime(timezone=True), nullable=False, index=True),
    Column("available_from", DateTime(timezone=True), nullable=False),
    Column("bid_exchange", String(20), nullable=False),
    Column("bid_price", Numeric(20, 8), nullable=False),
    Column("bid_size", BigInteger, nullable=False),
    Column("ask_exchange", String(20), nullable=False),
    Column("ask_price", Numeric(20, 8), nullable=False),
    Column("ask_size", BigInteger, nullable=False),
    Column("conditions", JSON, nullable=False),
    Column("tape", String(8), nullable=True),
    Column("source", String(40), nullable=False),
    Column("feed", String(20), nullable=False),
    Column("raw_object_id", String(36), nullable=False),
    Column("ingested_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint(
        "source",
        "feed",
        "quote_fingerprint",
        name="uq_market_quotes_provider_identity",
    ),
)

option_snapshots = Table(
    "option_snapshots",
    metadata,
    Column("option_snapshot_id", String(36), primary_key=True),
    Column("contract_symbol", String(32), nullable=False, index=True),
    Column("underlying_symbol", String(24), nullable=False, index=True),
    Column("as_of", DateTime(timezone=True), nullable=False, index=True),
    Column("available_from", DateTime(timezone=True), nullable=False),
    Column("bid_price", Numeric(20, 8), nullable=True),
    Column("bid_size", BigInteger, nullable=True),
    Column("ask_price", Numeric(20, 8), nullable=True),
    Column("ask_size", BigInteger, nullable=True),
    Column("last_trade_price", Numeric(20, 8), nullable=True),
    Column("last_trade_size", BigInteger, nullable=True),
    Column("implied_volatility", Numeric(20, 10), nullable=True),
    Column("delta", Numeric(20, 10), nullable=True),
    Column("gamma", Numeric(20, 10), nullable=True),
    Column("theta", Numeric(20, 10), nullable=True),
    Column("vega", Numeric(20, 10), nullable=True),
    Column("rho", Numeric(20, 10), nullable=True),
    Column("source", String(40), nullable=False),
    Column("feed", String(20), nullable=False),
    Column("raw_object_id", String(36), nullable=False),
    Column("ingested_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint(
        "source",
        "feed",
        "contract_symbol",
        "as_of",
        name="uq_option_snapshots_identity",
    ),
)

ingestion_runs = Table(
    "ingestion_runs",
    metadata,
    Column("ingestion_run_id", String(36), primary_key=True),
    Column("provider", String(40), nullable=False),
    Column("data_type", String(80), nullable=False),
    Column("status", String(24), nullable=False),
    Column("requested_at", DateTime(timezone=True), nullable=False),
    Column("completed_at", DateTime(timezone=True), nullable=True),
    Column("request_metadata", JSON, nullable=False),
    Column("pages_received", Integer, nullable=False, default=0),
    Column("records_received", Integer, nullable=False, default=0),
    Column("records_inserted", Integer, nullable=False, default=0),
    Column("error_code", String(80), nullable=True),
)

data_quality_reports = Table(
    "data_quality_reports",
    metadata,
    Column("data_quality_report_id", String(36), primary_key=True),
    Column("ruleset_version", String(80), nullable=False),
    Column("dataset_type", String(80), nullable=False, index=True),
    Column("symbol", String(24), nullable=False, index=True),
    Column("timeframe", String(16), nullable=False),
    Column("window_start", DateTime(timezone=True), nullable=True),
    Column("window_end", DateTime(timezone=True), nullable=True),
    Column("record_count", Integer, nullable=False),
    Column("data_sha256", String(64), nullable=False, index=True),
    Column("scope_sha256", String(64), nullable=False),
    Column("status", String(24), nullable=False, index=True),
    Column("checks_json", JSON, nullable=False),
    Column("issue_counts_json", JSON, nullable=False),
    Column("code_git_sha", String(64), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False, index=True),
    UniqueConstraint(
        "ruleset_version",
        "dataset_type",
        "symbol",
        "timeframe",
        "data_sha256",
        "scope_sha256",
        name="uq_data_quality_reports_dataset_hash",
    ),
)

workflow_jobs = Table(
    "workflow_jobs",
    metadata,
    Column("workflow_job_id", String(36), primary_key=True),
    Column("job_group_id", String(36), nullable=False, index=True),
    Column("job_type", String(80), nullable=False, index=True),
    Column("partition_key", String(160), nullable=False),
    Column("request_sha256", String(64), nullable=False),
    Column("payload_json", JSON, nullable=False),
    Column("status", String(24), nullable=False, index=True),
    Column("attempt_count", Integer, nullable=False),
    Column("max_attempts", Integer, nullable=False),
    Column("dependency_job_ids_json", JSON, nullable=False),
    Column("lease_owner", String(120), nullable=True, index=True),
    Column("lease_token", String(36), nullable=True, index=True),
    Column("lease_expires_at", DateTime(timezone=True), nullable=True, index=True),
    Column("cursor_json", JSON, nullable=False),
    Column("result_json", JSON, nullable=False),
    Column("error_code", String(120), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("started_at", DateTime(timezone=True), nullable=True),
    Column("updated_at", DateTime(timezone=True), nullable=False, index=True),
    Column("completed_at", DateTime(timezone=True), nullable=True),
    UniqueConstraint(
        "job_group_id",
        "partition_key",
        name="uq_workflow_jobs_group_partition",
    ),
)

reference_imports = Table(
    "reference_imports",
    metadata,
    Column("reference_import_id", String(36), primary_key=True),
    Column("dataset_type", String(80), nullable=False, index=True),
    Column("source", String(80), nullable=False),
    Column("source_version", String(120), nullable=False),
    Column("content_sha256", String(64), nullable=False),
    Column("records_received", Integer, nullable=False),
    Column("records_inserted", Integer, nullable=False),
    Column("status", String(24), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False, index=True),
    UniqueConstraint(
        "dataset_type",
        "source",
        "source_version",
        "content_sha256",
        name="uq_reference_imports_content",
    ),
)

entities = Table(
    "entities",
    metadata,
    Column("entity_id", String(36), primary_key=True),
    Column("primary_symbol", String(24), nullable=False, index=True),
    Column("canonical_name", Text, nullable=True),
    Column("cik", String(10), nullable=True, index=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint("primary_symbol", name="uq_entities_primary_symbol"),
    UniqueConstraint("cik", name="uq_entities_cik"),
)

entity_symbols = Table(
    "entity_symbols",
    metadata,
    Column(
        "entity_id",
        String(36),
        ForeignKey("entities.entity_id", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column("symbol", String(24), primary_key=True, index=True),
)

source_documents = Table(
    "source_documents",
    metadata,
    Column("document_id", String(36), primary_key=True),
    Column("provider", String(40), nullable=False),
    Column("provider_document_id", String(160), nullable=False),
    Column("canonical_url", Text, nullable=False),
    Column("source_kind", String(40), nullable=False, index=True),
    Column("source_tier", String(16), nullable=False, index=True),
    Column("publisher", Text, nullable=False),
    Column("published_at", DateTime(timezone=True), nullable=False, index=True),
    Column("first_seen_at", DateTime(timezone=True), nullable=False),
    Column("last_seen_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint(
        "provider",
        "provider_document_id",
        name="uq_source_documents_provider_identity",
    ),
)

source_document_versions = Table(
    "source_document_versions",
    metadata,
    Column("version_id", String(36), primary_key=True),
    Column(
        "document_id",
        String(36),
        ForeignKey("source_documents.document_id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    ),
    Column("content_sha256", String(64), nullable=False),
    Column("title", Text, nullable=False),
    Column("summary", Text, nullable=True),
    Column("body_text", Text, nullable=True),
    Column("corrected_at", DateTime(timezone=True), nullable=True),
    Column("ingested_at", DateTime(timezone=True), nullable=False, index=True),
    Column("raw_object_id", String(36), nullable=False),
    UniqueConstraint(
        "document_id",
        "content_sha256",
        name="uq_source_document_versions_content",
    ),
)

document_entities = Table(
    "document_entities",
    metadata,
    Column(
        "document_id",
        String(36),
        ForeignKey("source_documents.document_id", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "entity_id",
        String(36),
        ForeignKey("entities.entity_id", ondelete="CASCADE"),
        primary_key=True,
    ),
)

document_symbols = Table(
    "document_symbols",
    metadata,
    Column(
        "document_id",
        String(36),
        ForeignKey("source_documents.document_id", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column("symbol", String(24), primary_key=True, index=True),
)

catalysts = Table(
    "catalysts",
    metadata,
    Column("catalyst_id", String(36), primary_key=True),
    Column("canonical_key", String(64), nullable=False, unique=True),
    Column("catalyst_type", String(40), nullable=False, index=True),
    Column("primary_symbol", String(24), nullable=False, index=True),
    Column("event_time", DateTime(timezone=True), nullable=False, index=True),
    Column("available_from", DateTime(timezone=True), nullable=False),
    Column("last_updated_at", DateTime(timezone=True), nullable=False),
    Column("headline", Text, nullable=False),
    Column("primary_source_document_id", String(36), nullable=True),
    Column("status", String(24), nullable=False),
    Column("source_count", Integer, nullable=False),
)

catalyst_documents = Table(
    "catalyst_documents",
    metadata,
    Column(
        "catalyst_id",
        String(36),
        ForeignKey("catalysts.catalyst_id", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "document_id",
        String(36),
        ForeignKey("source_documents.document_id", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column("match_method", String(40), nullable=False),
    Column("match_score", Numeric(8, 6), nullable=False),
    Column("linked_at", DateTime(timezone=True), nullable=False),
)

corporate_facts = Table(
    "corporate_facts",
    metadata,
    Column("fact_id", String(36), primary_key=True),
    Column("fact_fingerprint", String(64), nullable=False, unique=True),
    Column("entity_id", String(36), nullable=True, index=True),
    Column("symbol", String(24), nullable=False, index=True),
    Column("cik", String(10), nullable=False, index=True),
    Column("issuer_name", Text, nullable=False),
    Column("taxonomy", String(80), nullable=False),
    Column("tag", String(160), nullable=False, index=True),
    Column("unit", String(40), nullable=False),
    Column("period_start", DateTime(timezone=True), nullable=True),
    Column("period_end", DateTime(timezone=True), nullable=False),
    Column("filed_at", DateTime(timezone=True), nullable=False, index=True),
    Column("accepted_at", DateTime(timezone=True), nullable=True),
    Column("fiscal_year", Integer, nullable=True),
    Column("fiscal_period", String(20), nullable=True),
    Column("form", String(20), nullable=False),
    Column("accession_number", String(32), nullable=True),
    Column("numeric_value", Numeric(30, 10), nullable=True),
    Column("value_text", Text, nullable=False),
    Column("available_from", DateTime(timezone=True), nullable=False),
    Column("raw_object_id", String(36), nullable=False),
    Column("ingested_at", DateTime(timezone=True), nullable=False),
)

corporate_actions = Table(
    "corporate_actions",
    metadata,
    Column("corporate_action_id", String(36), primary_key=True),
    Column("action_fingerprint", String(64), nullable=False, unique=True),
    Column("symbol", String(24), nullable=False, index=True),
    Column("action_type", String(32), nullable=False, index=True),
    Column("effective_at", DateTime(timezone=True), nullable=False, index=True),
    Column("available_from", DateTime(timezone=True), nullable=False, index=True),
    Column("split_ratio", Numeric(24, 10), nullable=True),
    Column("cash_amount", Numeric(24, 10), nullable=True),
    Column("currency", String(8), nullable=True),
    Column("new_symbol", String(24), nullable=True),
    Column("source", String(40), nullable=False),
    Column("raw_object_id", String(36), nullable=False),
    Column("ingested_at", DateTime(timezone=True), nullable=False),
)

universe_memberships = Table(
    "universe_memberships",
    metadata,
    Column("membership_id", String(36), primary_key=True),
    Column("universe", String(80), nullable=False, index=True),
    Column("symbol", String(24), nullable=False, index=True),
    Column("effective_from", DateTime(timezone=True), nullable=False, index=True),
    Column("effective_to", DateTime(timezone=True), nullable=True),
    Column("available_from", DateTime(timezone=True), nullable=False),
    Column("source", String(40), nullable=False),
    Column("source_version", String(80), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint(
        "universe",
        "symbol",
        "effective_from",
        "source",
        "source_version",
        name="uq_universe_memberships_identity",
    ),
)

evidence_packets = Table(
    "evidence_packets",
    metadata,
    Column("evidence_packet_id", String(36), primary_key=True),
    Column("symbol", String(24), nullable=False, index=True),
    Column("as_of", DateTime(timezone=True), nullable=False, index=True),
    Column("evidence_hash", String(64), nullable=False),
    Column("references_json", JSON, nullable=False),
    Column("source_max_available_from", DateTime(timezone=True), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint(
        "symbol",
        "as_of",
        "evidence_hash",
        name="uq_evidence_packets_identity",
    ),
)

feature_snapshots = Table(
    "feature_snapshots",
    metadata,
    Column("feature_snapshot_id", String(36), primary_key=True),
    Column(
        "evidence_packet_id",
        String(36),
        ForeignKey("evidence_packets.evidence_packet_id"),
        nullable=False,
        index=True,
    ),
    Column("symbol", String(24), nullable=False, index=True),
    Column("timeframe", String(16), nullable=False),
    Column("as_of", DateTime(timezone=True), nullable=False, index=True),
    Column("feature_set_version", String(80), nullable=False),
    Column("feature_values", JSON, nullable=False),
    Column("source_max_available_from", DateTime(timezone=True), nullable=False),
    Column("data_hash", String(64), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint(
        "symbol",
        "timeframe",
        "as_of",
        "feature_set_version",
        "data_hash",
        name="uq_feature_snapshots_identity",
    ),
)

strategy_specs = Table(
    "strategy_specs",
    metadata,
    Column("strategy_spec_id", String(36), primary_key=True),
    Column("name", String(120), nullable=False),
    Column("version", String(120), nullable=False),
    Column("strategy_type", String(80), nullable=False),
    Column("timeframe", String(16), nullable=False),
    Column("feature_set_version", String(80), nullable=False),
    Column("parameters_json", JSON, nullable=False),
    Column("data_requirements_json", JSON, nullable=False),
    Column("code_sha256", String(64), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint("name", "version", name="uq_strategy_specs_name_version"),
)

strategy_generation_attempts = Table(
    "strategy_generation_attempts",
    metadata,
    Column("generation_attempt_id", String(36), primary_key=True),
    Column("feature_snapshot_id", String(36), nullable=False, index=True),
    Column("analysis_id", String(36), nullable=False, index=True),
    Column("forecast_id", String(36), nullable=False, index=True),
    Column("status", String(24), nullable=False, index=True),
    Column("provider", String(24), nullable=True),
    Column("generation_invocation_id", String(36), nullable=True),
    Column("critique_invocation_id", String(36), nullable=True),
    Column(
        "strategy_spec_id",
        String(36),
        ForeignKey("strategy_specs.strategy_spec_id"),
        nullable=True,
        index=True,
    ),
    Column("proposal_json", JSON, nullable=True),
    Column("critique_json", JSON, nullable=True),
    Column("error_code", String(120), nullable=True),
    Column("error_message", Text, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False, index=True),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

experiment_runs = Table(
    "experiment_runs",
    metadata,
    Column("experiment_run_id", String(36), primary_key=True),
    Column(
        "strategy_spec_id",
        String(36),
        ForeignKey("strategy_specs.strategy_spec_id"),
        nullable=False,
        index=True,
    ),
    Column("symbol", String(24), nullable=False, index=True),
    Column("timeframe", String(16), nullable=False),
    Column("as_of_start", DateTime(timezone=True), nullable=False),
    Column("as_of_end", DateTime(timezone=True), nullable=False),
    Column("dataset_hash", String(64), nullable=False, index=True),
    Column("code_git_sha", String(64), nullable=False),
    Column("status", String(24), nullable=False, index=True),
    Column("cost_model_json", JSON, nullable=False),
    Column("metrics_json", JSON, nullable=False),
    Column("feature_snapshot_ids", JSON, nullable=False),
    Column("started_at", DateTime(timezone=True), nullable=False),
    Column("finished_at", DateTime(timezone=True), nullable=False),
)

backtest_trades = Table(
    "backtest_trades",
    metadata,
    Column("trade_id", String(36), primary_key=True),
    Column(
        "experiment_run_id",
        String(36),
        ForeignKey(
            "experiment_runs.experiment_run_id",
            name="fk_bt_events_experiment",
            ondelete="CASCADE",
        ),
        nullable=False,
        index=True,
    ),
    Column("symbol", String(24), nullable=False, index=True),
    Column("action", String(16), nullable=False),
    Column("signal_as_of", DateTime(timezone=True), nullable=False),
    Column("entry_time", DateTime(timezone=True), nullable=False),
    Column("exit_time", DateTime(timezone=True), nullable=False),
    Column("quantity", BigInteger, nullable=False),
    Column("exit_quantity", Numeric(24, 10), nullable=True),
    Column("entry_price", Numeric(20, 8), nullable=False),
    Column("exit_price", Numeric(20, 8), nullable=False),
    Column("gross_pnl", Numeric(24, 8), nullable=False),
    Column("corporate_action_cash", Numeric(24, 8), nullable=False, default=0),
    Column("transaction_cost", Numeric(24, 8), nullable=False),
    Column("net_pnl", Numeric(24, 8), nullable=False),
    Column(
        "feature_snapshot_id",
        String(36),
        ForeignKey("feature_snapshots.feature_snapshot_id"),
        nullable=False,
    ),
    Column("exit_reason", String(80), nullable=False),
)

backtest_portfolio_events = Table(
    "backtest_portfolio_events",
    metadata,
    Column("portfolio_event_id", String(36), primary_key=True),
    Column(
        "experiment_run_id",
        String(36),
        ForeignKey("experiment_runs.experiment_run_id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    ),
    Column("sequence", Integer, nullable=False),
    Column("event_type", String(32), nullable=False, index=True),
    Column("event_time", DateTime(timezone=True), nullable=False, index=True),
    Column("symbol", String(24), nullable=False, index=True),
    Column("cash_balance", Numeric(24, 8), nullable=False),
    Column("position_quantity", Numeric(24, 10), nullable=False),
    Column("cash_delta", Numeric(24, 8), nullable=False),
    Column("quantity_delta", Numeric(24, 10), nullable=False),
    Column("price", Numeric(20, 8), nullable=True),
    Column(
        "corporate_action_id",
        String(36),
        ForeignKey(
            "corporate_actions.corporate_action_id",
            name="fk_bt_events_action",
        ),
        nullable=True,
    ),
    Column(
        "feature_snapshot_id",
        String(36),
        ForeignKey(
            "feature_snapshots.feature_snapshot_id",
            name="fk_bt_events_feature",
        ),
        nullable=True,
    ),
    Column("details_json", JSON, nullable=False),
    UniqueConstraint(
        "experiment_run_id",
        "sequence",
        name="uq_backtest_portfolio_events_sequence",
    ),
)

feature_parity_checks = Table(
    "feature_parity_checks",
    metadata,
    Column("parity_check_id", String(36), primary_key=True),
    Column("symbol", String(24), nullable=False, index=True),
    Column("timeframe", String(16), nullable=False),
    Column("as_of", DateTime(timezone=True), nullable=False, index=True),
    Column("feature_set_version", String(80), nullable=False),
    Column("offline_data_hash", String(64), nullable=False),
    Column("online_data_hash", String(64), nullable=False),
    Column("matched", Boolean, nullable=False),
    Column("checked_at", DateTime(timezone=True), nullable=False),
)

validation_reports = Table(
    "validation_reports",
    metadata,
    Column("validation_report_id", String(36), primary_key=True),
    Column("symbol", String(24), nullable=False, index=True),
    Column("timeframe", String(16), nullable=False),
    Column("strategy_types", JSON, nullable=False),
    Column("validation_subject", String(32), nullable=False),
    Column("validated_strategy_spec_ids", JSON, nullable=False),
    Column("execution_contract_json", JSON, nullable=False),
    Column("execution_contract_sha256", String(64), nullable=False, index=True),
    Column("selection_metric", String(40), nullable=False),
    Column("train_bars", Integer, nullable=False),
    Column("test_bars", Integer, nullable=False),
    Column("step_bars", Integer, nullable=False),
    Column("embargo_bars", Integer, nullable=False),
    Column("aggregate_metrics", JSON, nullable=False),
    Column("regime_metrics", JSON, nullable=False),
    Column("robustness_metrics", JSON, nullable=False),
    Column("gate_assessment", JSON, nullable=False),
    Column("report_hash", String(64), nullable=False, index=True),
    Column("code_git_sha", String(64), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False, index=True),
)

validation_folds = Table(
    "validation_folds",
    metadata,
    Column("validation_fold_id", String(36), primary_key=True),
    Column(
        "validation_report_id",
        String(36),
        ForeignKey(
            "validation_reports.validation_report_id",
            name="fk_validation_folds_report",
            ondelete="CASCADE",
        ),
        nullable=False,
        index=True,
    ),
    Column("fold_number", Integer, nullable=False),
    Column("train_start", DateTime(timezone=True), nullable=False),
    Column("train_end", DateTime(timezone=True), nullable=False),
    Column("test_start", DateTime(timezone=True), nullable=False),
    Column("test_end", DateTime(timezone=True), nullable=False),
    Column("selected_strategy", String(80), nullable=False),
    Column("selection_metric", String(40), nullable=False),
    Column("train_experiment_ids", JSON, nullable=False),
    Column("test_experiment_ids", JSON, nullable=False),
    Column("selected_train_metrics", JSON, nullable=False),
    Column("selected_test_metrics", JSON, nullable=False),
    Column("selected_test_rank", Integer, nullable=False),
    Column("regime", String(24), nullable=False, index=True),
    UniqueConstraint(
        "validation_report_id",
        "fold_number",
        name="uq_validation_folds_report_number",
    ),
)

llm_invocations = Table(
    "llm_invocations",
    metadata,
    Column("invocation_id", String(36), primary_key=True),
    Column("workload", String(80), nullable=False, index=True),
    Column("routing_version", String(80), nullable=False),
    Column("routing_sha256", String(64), nullable=False),
    Column("code_git_sha", String(64), nullable=False),
    Column("provider", String(40), nullable=False, index=True),
    Column("model", String(120), nullable=False, index=True),
    Column("reasoning_effort", String(24), nullable=False),
    Column("prompt_version", String(120), nullable=False),
    Column("request_sha256", String(64), nullable=False, index=True),
    Column("input_sha256", String(64), nullable=False),
    Column("request_envelope_json", JSON, nullable=True),
    Column("response_id", String(160), nullable=True),
    Column("output_text", Text, nullable=True),
    Column("output_sha256", String(64), nullable=True),
    Column("usage_json", JSON, nullable=False),
    Column("latency_ms", Integer, nullable=False),
    Column("status", String(24), nullable=False, index=True),
    Column("error_code", String(120), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False, index=True),
    Column("completed_at", DateTime(timezone=True), nullable=False),
)

llm_routing_revisions = Table(
    "llm_routing_revisions",
    metadata,
    Column("routing_revision_id", String(36), primary_key=True),
    Column("base_routing_version", String(80), nullable=False),
    Column("base_routing_sha256", String(64), nullable=False, index=True),
    Column("routing_version", String(120), nullable=False, unique=True),
    Column("routing_sha256", String(64), nullable=False),
    Column("routes_json", JSON, nullable=False),
    Column("reason", Text, nullable=False),
    Column("created_by", String(80), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False, index=True),
)

llm_budget_revisions = Table(
    "llm_budget_revisions",
    metadata,
    Column("budget_revision_id", String(36), primary_key=True),
    Column("base_policy_version", String(80), nullable=False),
    Column("base_policy_sha256", String(64), nullable=False, index=True),
    Column("policy_version", String(120), nullable=False, unique=True),
    Column("policy_sha256", String(64), nullable=False),
    Column("workload_limits_json", JSON, nullable=False),
    Column("reason", Text, nullable=False),
    Column("created_by", String(80), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False, index=True),
)

llm_budget_windows = Table(
    "llm_budget_windows",
    metadata,
    Column("window_key", String(180), primary_key=True),
    Column("policy_version", String(80), nullable=False),
    Column("scope", String(120), nullable=False, index=True),
    Column("period_kind", String(16), nullable=False),
    Column("period_start", DateTime(timezone=True), nullable=False, index=True),
    Column("token_limit", BigInteger, nullable=False),
    Column("cost_limit_microusd", BigInteger, nullable=False),
    Column("reserved_tokens", BigInteger, nullable=False),
    Column("consumed_tokens", BigInteger, nullable=False),
    Column("reserved_cost_microusd", BigInteger, nullable=False),
    Column("consumed_cost_microusd", BigInteger, nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

llm_budget_reservations = Table(
    "llm_budget_reservations",
    metadata,
    Column("invocation_id", String(36), primary_key=True),
    Column("policy_version", String(80), nullable=False),
    Column("provider", String(40), nullable=False, index=True),
    Column("workload", String(80), nullable=False, index=True),
    Column("reserved_input_tokens", BigInteger, nullable=False),
    Column("reserved_output_tokens", BigInteger, nullable=False),
    Column("reserved_cost_microusd", BigInteger, nullable=False),
    Column("actual_input_tokens", BigInteger, nullable=True),
    Column("actual_output_tokens", BigInteger, nullable=True),
    Column("actual_cost_microusd", BigInteger, nullable=True),
    Column("window_keys_json", JSON, nullable=False),
    Column("status", String(24), nullable=False, index=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("settled_at", DateTime(timezone=True), nullable=True),
)

research_analyses = Table(
    "research_analyses",
    metadata,
    Column("analysis_id", String(36), primary_key=True),
    Column("symbol", String(24), nullable=False, index=True),
    Column("as_of", DateTime(timezone=True), nullable=False, index=True),
    Column("status", String(24), nullable=False, index=True),
    Column("schema_version", String(80), nullable=False),
    Column("prompt_version", String(80), nullable=False),
    Column("evidence_bundle_hash", String(64), nullable=False, index=True),
    Column("evidence_bundle_json", JSON, nullable=False),
    Column(
        "feature_snapshot_id",
        String(36),
        ForeignKey("feature_snapshots.feature_snapshot_id"),
        nullable=False,
        index=True,
    ),
    Column(
        "forecast_id",
        String(36),
        ForeignKey("ml_forecasts.forecast_id"),
        nullable=True,
        index=True,
    ),
    Column(
        "llm_invocation_id",
        String(36),
        ForeignKey("llm_invocations.invocation_id"),
        nullable=True,
        index=True,
    ),
    Column("analysis_json", JSON, nullable=True),
    Column("citation_validation_json", JSON, nullable=False),
    Column("rejection_reason", String(240), nullable=True),
    Column("code_git_sha", String(64), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False, index=True),
)

ml_training_runs = Table(
    "ml_training_runs",
    metadata,
    Column("training_run_id", String(36), primary_key=True),
    Column("symbol", String(24), nullable=False, index=True),
    Column("timeframe", String(16), nullable=False),
    Column("horizon_bars", Integer, nullable=False),
    Column("feature_set_version", String(80), nullable=False),
    Column("dataset_sha256", String(64), nullable=False, index=True),
    Column("training_contract_sha256", String(64), nullable=False, index=True),
    Column("sample_count", Integer, nullable=False),
    Column("fold_count", Integer, nullable=False),
    Column("embargo_bars", Integer, nullable=False),
    Column("model_ids_json", JSON, nullable=False),
    Column("selected_model_id", String(36), nullable=False),
    Column("selection_metric", String(160), nullable=False),
    Column("status", String(24), nullable=False, index=True),
    Column("code_git_sha", String(64), nullable=False),
    Column("started_at", DateTime(timezone=True), nullable=False),
    Column("finished_at", DateTime(timezone=True), nullable=False, index=True),
)

ml_models = Table(
    "ml_models",
    metadata,
    Column("model_id", String(36), primary_key=True),
    Column(
        "training_run_id",
        String(36),
        ForeignKey("ml_training_runs.training_run_id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    ),
    Column("model_name", String(120), nullable=False, index=True),
    Column("model_version", String(160), nullable=False, unique=True),
    Column("kind", String(40), nullable=False),
    Column("symbol", String(24), nullable=False, index=True),
    Column("timeframe", String(16), nullable=False),
    Column("horizon_bars", Integer, nullable=False),
    Column("feature_set_version", String(80), nullable=False),
    Column("feature_names_json", JSON, nullable=False),
    Column("training_start", DateTime(timezone=True), nullable=False),
    Column("training_end", DateTime(timezone=True), nullable=False),
    Column("training_data_cutoff", DateTime(timezone=True), nullable=False),
    Column("artifact_json", JSON, nullable=False),
    Column("artifact_sha256", String(64), nullable=False),
    Column("metrics_json", JSON, nullable=False),
    Column("calibration_json", JSON, nullable=False),
    Column("drift_json", JSON, nullable=False),
    Column("promotion_assessment_json", JSON, nullable=False),
    Column("status", String(24), nullable=False, index=True),
    Column("champion_slot", String(180), nullable=True, unique=True),
    Column("code_git_sha", String(64), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False, index=True),
)

ml_forecasts = Table(
    "ml_forecasts",
    metadata,
    Column("forecast_id", String(36), primary_key=True),
    Column(
        "model_id",
        String(36),
        ForeignKey("ml_models.model_id"),
        nullable=False,
        index=True,
    ),
    Column("symbol", String(24), nullable=False, index=True),
    Column("as_of", DateTime(timezone=True), nullable=False, index=True),
    Column("horizon", String(40), nullable=False),
    Column("expected_return", Numeric(24, 12), nullable=False),
    Column("probability_up", Numeric(18, 12), nullable=False),
    Column("uncertainty", Numeric(18, 12), nullable=False),
    Column("model_version", String(160), nullable=False),
    Column("training_data_cutoff", DateTime(timezone=True), nullable=False),
    Column(
        "feature_snapshot_id",
        String(36),
        ForeignKey("feature_snapshots.feature_snapshot_id"),
        nullable=False,
        index=True,
    ),
    Column("created_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint(
        "model_id",
        "feature_snapshot_id",
        "horizon",
        name="uq_ml_forecasts_model_feature_horizon",
    ),
)

model_registry_events = Table(
    "model_registry_events",
    metadata,
    Column("registry_event_id", String(36), primary_key=True),
    Column(
        "model_id",
        String(36),
        ForeignKey("ml_models.model_id"),
        nullable=False,
        index=True,
    ),
    Column("previous_status", String(24), nullable=False),
    Column("new_status", String(24), nullable=False, index=True),
    Column(
        "training_run_id",
        String(36),
        ForeignKey("ml_training_runs.training_run_id"),
        nullable=False,
    ),
    Column("approved_by", String(80), nullable=False),
    Column("reason", Text, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False, index=True),
)

admin_sessions = Table(
    "admin_sessions",
    metadata,
    Column("session_id", String(36), primary_key=True),
    Column("token_sha256", String(64), nullable=False, unique=True),
    Column("username", String(80), nullable=False, index=True),
    Column("credential_fingerprint", String(64), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("last_seen_at", DateTime(timezone=True), nullable=False, index=True),
    Column("expires_at", DateTime(timezone=True), nullable=False, index=True),
    Column("revoked_at", DateTime(timezone=True), nullable=True),
    Column("user_agent_sha256", String(64), nullable=True),
    Column("client_ip_sha256", String(64), nullable=True),
)

admin_auth_events = Table(
    "admin_auth_events",
    metadata,
    Column("auth_event_id", String(36), primary_key=True),
    Column("event_type", String(40), nullable=False, index=True),
    Column("username", String(80), nullable=False, index=True),
    Column("success", Boolean, nullable=False, index=True),
    Column("detail", String(160), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False, index=True),
)

system_lists = Table(
    "system_lists",
    metadata,
    Column("list_id", String(36), primary_key=True),
    Column("slug", String(80), nullable=False, unique=True),
    Column("list_type", String(40), nullable=False, index=True),
    Column("name", String(120), nullable=False),
    Column("description", Text, nullable=False),
    Column("mode", String(24), nullable=False),
    Column("status", String(24), nullable=False, index=True),
    Column("current_revision", Integer, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False, index=True),
)

system_list_revisions = Table(
    "system_list_revisions",
    metadata,
    Column("list_revision_id", String(36), primary_key=True),
    Column(
        "list_id",
        String(36),
        ForeignKey("system_lists.list_id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    ),
    Column("revision_number", Integer, nullable=False),
    Column("members_json", JSON, nullable=False),
    Column("reason", Text, nullable=False),
    Column("created_by", String(80), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False, index=True),
    UniqueConstraint(
        "list_id",
        "revision_number",
        name="uq_system_list_revisions_number",
    ),
)

object_threads = Table(
    "object_threads",
    metadata,
    Column("thread_id", String(36), primary_key=True),
    Column("object_type", String(60), nullable=False, index=True),
    Column("object_id", String(160), nullable=False, index=True),
    Column("title", String(240), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False, index=True),
    UniqueConstraint("object_type", "object_id", name="uq_object_threads_object"),
)

thread_posts = Table(
    "thread_posts",
    metadata,
    Column("post_id", String(36), primary_key=True),
    Column(
        "thread_id",
        String(36),
        ForeignKey("object_threads.thread_id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    ),
    Column("author_kind", String(24), nullable=False),
    Column("author_name", String(80), nullable=False),
    Column("body", Text, nullable=False),
    Column("metadata_json", JSON, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False, index=True),
)

admin_action_requests = Table(
    "admin_action_requests",
    metadata,
    Column("action_request_id", String(36), primary_key=True),
    Column("action_type", String(80), nullable=False, index=True),
    Column("target_type", String(60), nullable=False, index=True),
    Column("target_id", String(160), nullable=False, index=True),
    Column("parameters_json", JSON, nullable=False),
    Column("reason", Text, nullable=False),
    Column("preview_json", JSON, nullable=False),
    Column("status", String(24), nullable=False, index=True),
    Column("requested_by", String(80), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False, index=True),
    Column("expires_at", DateTime(timezone=True), nullable=False),
    Column("confirmed_at", DateTime(timezone=True), nullable=True),
    Column("executed_at", DateTime(timezone=True), nullable=True),
    Column("result_json", JSON, nullable=False),
    Column("error_code", String(120), nullable=True),
)

steward_conversations = Table(
    "steward_conversations",
    metadata,
    Column("conversation_id", String(36), primary_key=True),
    Column("title", String(160), nullable=False),
    Column("created_by", String(80), nullable=False),
    Column("context_object_type", String(60), nullable=True),
    Column("context_object_id", String(160), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False, index=True),
)

steward_messages = Table(
    "steward_messages",
    metadata,
    Column("message_id", String(36), primary_key=True),
    Column(
        "conversation_id",
        String(36),
        ForeignKey("steward_conversations.conversation_id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    ),
    Column("role", String(24), nullable=False),
    Column("content", Text, nullable=False),
    Column("citations_json", JSON, nullable=False),
    Column(
        "action_request_id",
        String(36),
        ForeignKey("admin_action_requests.action_request_id"),
        nullable=True,
        index=True,
    ),
    Column(
        "llm_invocation_id",
        String(36),
        ForeignKey("llm_invocations.invocation_id"),
        nullable=True,
        index=True,
    ),
    Column("created_at", DateTime(timezone=True), nullable=False, index=True),
)

strategy_adoptions = Table(
    "strategy_adoptions",
    metadata,
    Column("adoption_id", String(36), primary_key=True),
    Column(
        "strategy_spec_id",
        String(36),
        ForeignKey("strategy_specs.strategy_spec_id"),
        nullable=False,
        index=True,
    ),
    Column("status", String(32), nullable=False, index=True),
    Column(
        "validation_report_id",
        String(36),
        ForeignKey("validation_reports.validation_report_id"),
        nullable=True,
        index=True,
    ),
    Column("reason", Text, nullable=False),
    Column("approved_by", String(80), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False, index=True),
    UniqueConstraint(
        "strategy_spec_id",
        name="uq_strategy_adoptions_strategy_spec_id",
    ),
)

virtual_accounts = Table(
    "virtual_accounts",
    metadata,
    Column("virtual_account_id", String(36), primary_key=True),
    Column("slug", String(80), nullable=False, unique=True),
    Column("name", String(120), nullable=False),
    Column("account_type", String(32), nullable=False),
    Column("currency", String(8), nullable=False),
    Column("status", String(24), nullable=False, index=True),
    Column("initial_cash", Numeric(24, 8), nullable=False),
    Column("cash_balance", Numeric(24, 8), nullable=False),
    Column("realized_pnl", Numeric(24, 8), nullable=False),
    Column("reserved_cash", Numeric(24, 8), nullable=False),
    Column("reserved_risk_usd", Numeric(24, 8), nullable=False),
    Column("base_policy_version", String(80), nullable=False),
    Column("risk_revision", Integer, nullable=False),
    Column("baseline_stop_fraction", Numeric(12, 8), nullable=False),
    Column("baseline_target_r_multiple", Numeric(12, 8), nullable=False),
    Column("initial_risk_fraction", Numeric(12, 8), nullable=False),
    Column("maximum_trade_risk_usd", Numeric(24, 8), nullable=False),
    Column("maximum_concurrent_risk_usd", Numeric(24, 8), nullable=False),
    Column("daily_loss_stop_usd", Numeric(24, 8), nullable=False),
    Column("account_floor_usd", Numeric(24, 8), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False, index=True),
)

virtual_account_risk_revisions = Table(
    "virtual_account_risk_revisions",
    metadata,
    Column("risk_revision_id", String(36), primary_key=True),
    Column(
        "virtual_account_id",
        String(36),
        ForeignKey("virtual_accounts.virtual_account_id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    ),
    Column("revision_number", Integer, nullable=False),
    Column("baseline_stop_fraction", Numeric(12, 8), nullable=False),
    Column("baseline_target_r_multiple", Numeric(12, 8), nullable=False),
    Column("initial_risk_fraction", Numeric(12, 8), nullable=False),
    Column("maximum_trade_risk_usd", Numeric(24, 8), nullable=False),
    Column("maximum_concurrent_risk_usd", Numeric(24, 8), nullable=False),
    Column("daily_loss_stop_usd", Numeric(24, 8), nullable=False),
    Column("account_floor_usd", Numeric(24, 8), nullable=False),
    Column("reason", Text, nullable=False),
    Column("created_by", String(80), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint(
        "virtual_account_id",
        "revision_number",
        name="uq_virtual_account_risk_revisions_number",
    ),
)

strategy_sleeves = Table(
    "strategy_sleeves",
    metadata,
    Column("strategy_sleeve_id", String(36), primary_key=True),
    Column(
        "virtual_account_id",
        String(36),
        ForeignKey("virtual_accounts.virtual_account_id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    ),
    Column(
        "strategy_spec_id",
        String(36),
        ForeignKey("strategy_specs.strategy_spec_id"),
        nullable=False,
        index=True,
    ),
    Column("symbol", String(24), nullable=False, index=True),
    Column("status", String(24), nullable=False, index=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint(
        "virtual_account_id",
        "strategy_spec_id",
        "symbol",
        name="uq_strategy_sleeves_account_strategy_symbol",
    ),
)

shadow_deployments = Table(
    "shadow_deployments",
    metadata,
    Column("shadow_deployment_id", String(36), primary_key=True),
    Column(
        "virtual_account_id",
        String(36),
        ForeignKey("virtual_accounts.virtual_account_id"),
        nullable=False,
        index=True,
    ),
    Column(
        "strategy_sleeve_id",
        String(36),
        ForeignKey("strategy_sleeves.strategy_sleeve_id"),
        # Existing deployments are repaired to a deterministic sleeve lazily after
        # migration 0027. Every newly-created deployment supplies this value.
        nullable=True,
        index=True,
    ),
    Column(
        "strategy_spec_id",
        String(36),
        ForeignKey("strategy_specs.strategy_spec_id"),
        nullable=False,
        index=True,
    ),
    Column(
        "adoption_id",
        String(36),
        ForeignKey("strategy_adoptions.adoption_id"),
        nullable=True,
        index=True,
    ),
    Column("symbol", String(24), nullable=False, index=True),
    Column("status", String(24), nullable=False, index=True),
    Column("initial_cash", Numeric(24, 8), nullable=False),
    Column("cash_balance", Numeric(24, 8), nullable=False),
    Column("position_quantity", Numeric(24, 10), nullable=False),
    Column("average_entry_price", Numeric(20, 8), nullable=True),
    Column("last_price", Numeric(20, 8), nullable=True),
    Column("realized_pnl", Numeric(24, 8), nullable=False),
    Column("unrealized_pnl", Numeric(24, 8), nullable=False),
    Column("last_processed_bar_time", DateTime(timezone=True), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False, index=True),
    UniqueConstraint(
        "strategy_spec_id",
        "symbol",
        name="uq_shadow_deployments_strategy_symbol",
    ),
)

shadow_runs = Table(
    "shadow_runs",
    metadata,
    Column("shadow_run_id", String(36), primary_key=True),
    Column("status", String(24), nullable=False, index=True),
    Column("trigger", String(40), nullable=False),
    Column("deployment_count", Integer, nullable=False),
    Column("bars_processed", Integer, nullable=False),
    Column("events_created", Integer, nullable=False),
    Column("started_at", DateTime(timezone=True), nullable=False),
    Column("finished_at", DateTime(timezone=True), nullable=False, index=True),
    Column("error_code", String(120), nullable=True),
)

shadow_events = Table(
    "shadow_events",
    metadata,
    Column("shadow_event_id", String(36), primary_key=True),
    Column(
        "shadow_deployment_id",
        String(36),
        ForeignKey("shadow_deployments.shadow_deployment_id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    ),
    Column("shadow_run_id", String(36), nullable=True, index=True),
    Column("sequence", Integer, nullable=False),
    Column("event_type", String(40), nullable=False, index=True),
    Column("event_time", DateTime(timezone=True), nullable=False, index=True),
    Column("symbol", String(24), nullable=False, index=True),
    Column("bar_id", String(36), nullable=True, index=True),
    Column("cash_balance", Numeric(24, 8), nullable=False),
    Column("position_quantity", Numeric(24, 10), nullable=False),
    Column("price", Numeric(20, 8), nullable=True),
    Column("realized_pnl_delta", Numeric(24, 8), nullable=False),
    Column("payload_json", JSON, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint(
        "shadow_deployment_id",
        "sequence",
        name="uq_shadow_events_deployment_sequence",
    ),
    UniqueConstraint(
        "shadow_deployment_id",
        "bar_id",
        "event_type",
        name="uq_shadow_events_bar_type",
    ),
)

shadow_signal_candidates = Table(
    "shadow_signal_candidates",
    metadata,
    Column("candidate_id", String(36), primary_key=True),
    Column(
        "shadow_deployment_id",
        String(36),
        ForeignKey("shadow_deployments.shadow_deployment_id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    ),
    Column("shadow_run_id", String(36), nullable=False, index=True),
    Column(
        "strategy_spec_id",
        String(36),
        ForeignKey("strategy_specs.strategy_spec_id"),
        nullable=False,
        index=True,
    ),
    Column(
        "feature_snapshot_id",
        String(36),
        ForeignKey("feature_snapshots.feature_snapshot_id"),
        nullable=False,
        index=True,
    ),
    Column("decision_bar_id", String(36), nullable=False, index=True),
    Column("symbol", String(24), nullable=False, index=True),
    Column("action", String(16), nullable=False),
    Column("as_of", DateTime(timezone=True), nullable=False),
    Column("planned_entry", Numeric(20, 8), nullable=False),
    Column("invalidation", Numeric(20, 8), nullable=False),
    Column("targets_json", JSON, nullable=False),
    Column("expires_at", DateTime(timezone=True), nullable=False),
    Column("execution_contract_sha256", String(64), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint(
        "shadow_deployment_id",
        "decision_bar_id",
        name="uq_shadow_candidate_deployment_bar",
    ),
)

shadow_risk_decisions = Table(
    "shadow_risk_decisions",
    metadata,
    Column("risk_decision_id", String(36), primary_key=True),
    Column(
        "candidate_id",
        String(36),
        ForeignKey("shadow_signal_candidates.candidate_id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
    ),
    Column("verdict", String(16), nullable=False, index=True),
    Column("reason_codes_json", JSON, nullable=False),
    Column("account_equity", Numeric(24, 8), nullable=False),
    Column("daily_pnl", Numeric(24, 8), nullable=False),
    Column("concurrent_planned_risk", Numeric(24, 8), nullable=False),
    Column("risk_budget_usd", Numeric(24, 8), nullable=False),
    Column("max_quantity", Integer, nullable=False),
    Column("planned_entry", Numeric(20, 8), nullable=False),
    Column("invalidation", Numeric(20, 8), nullable=False),
    Column("planned_r_multiple_to_t1", Numeric(20, 8), nullable=True),
    Column("portfolio_risk_after_usd", Numeric(24, 8), nullable=False),
    Column("policy_version", String(80), nullable=False),
    Column("evaluation_context_json", JSON, nullable=False),
    Column("evaluated_at", DateTime(timezone=True), nullable=False, index=True),
)

shadow_trade_plans = Table(
    "shadow_trade_plans",
    metadata,
    Column("trade_plan_id", String(36), primary_key=True),
    Column(
        "candidate_id",
        String(36),
        ForeignKey("shadow_signal_candidates.candidate_id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
    ),
    Column(
        "risk_decision_id",
        String(36),
        ForeignKey("shadow_risk_decisions.risk_decision_id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
    ),
    Column("symbol", String(24), nullable=False, index=True),
    Column("direction", String(16), nullable=False),
    Column("quantity", Integer, nullable=False),
    Column("reserved_cash", Numeric(24, 8), nullable=False),
    Column("reserved_risk_usd", Numeric(24, 8), nullable=False),
    Column("limit_price", Numeric(20, 8), nullable=False),
    Column("invalidation", Numeric(20, 8), nullable=False),
    Column("targets_json", JSON, nullable=False),
    Column("expires_at", DateTime(timezone=True), nullable=False),
    Column("status", String(24), nullable=False, index=True),
    Column("opened_at", DateTime(timezone=True), nullable=True),
    Column("entry_raw_price", Numeric(20, 8), nullable=True),
    Column("entry_fill_price", Numeric(20, 8), nullable=True),
    Column("entry_commission", Numeric(24, 8), nullable=True),
    Column("filled_quantity", Numeric(24, 10), nullable=True),
    Column("starting_cash", Numeric(24, 8), nullable=True),
    Column("corporate_action_cash", Numeric(24, 8), nullable=True),
    Column("applied_corporate_action_ids_json", JSON, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("closed_at", DateTime(timezone=True), nullable=True),
)

paper_enrollments = Table(
    "paper_enrollments",
    metadata,
    Column("paper_enrollment_id", String(36), primary_key=True),
    Column(
        "shadow_deployment_id",
        String(36),
        ForeignKey("shadow_deployments.shadow_deployment_id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    ),
    Column("broker_account_id", String(80), nullable=True, index=True),
    Column("status", String(24), nullable=False, index=True),
    Column("created_by", String(80), nullable=False),
    Column("reason", Text, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint(
        "shadow_deployment_id",
        name="uq_paper_enrollments_shadow_deployment_id",
    ),
)

paper_orders = Table(
    "paper_orders",
    metadata,
    Column("paper_order_id", String(36), primary_key=True),
    Column(
        "paper_enrollment_id",
        String(36),
        ForeignKey("paper_enrollments.paper_enrollment_id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    ),
    Column(
        "shadow_trade_plan_id",
        String(36),
        ForeignKey("shadow_trade_plans.trade_plan_id"),
        nullable=False,
        index=True,
    ),
    Column("client_order_id", String(48), nullable=False, unique=True),
    Column("broker_order_id", String(80), nullable=True, unique=True),
    Column("broker_account_id", String(80), nullable=True, index=True),
    Column("symbol", String(24), nullable=False, index=True),
    Column("side", String(8), nullable=False),
    Column("quantity", Numeric(24, 10), nullable=False),
    Column("order_type", String(24), nullable=False),
    Column("time_in_force", String(16), nullable=False),
    Column("order_class", String(24), nullable=False),
    Column("entry_limit_price", Numeric(20, 8), nullable=False),
    Column("take_profit_price", Numeric(20, 8), nullable=False),
    Column("stop_loss_price", Numeric(20, 8), nullable=False),
    Column("plan_expires_at", DateTime(timezone=True), nullable=False),
    Column("status", String(40), nullable=False, index=True),
    Column("lifecycle_complete", Boolean, nullable=False),
    Column("submission_attempts", Integer, nullable=False),
    Column("filled_quantity", Numeric(24, 10), nullable=False),
    Column("filled_average_price", Numeric(20, 8), nullable=True),
    Column("broker_payload_json", JSON, nullable=False),
    Column("error_code", String(120), nullable=True),
    Column("error_message", Text, nullable=True),
    Column("submitted_at", DateTime(timezone=True), nullable=True),
    Column("last_reconciled_at", DateTime(timezone=True), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False, index=True),
    UniqueConstraint(
        "shadow_trade_plan_id",
        name="uq_paper_orders_shadow_trade_plan_id",
    ),
)

paper_order_legs = Table(
    "paper_order_legs",
    metadata,
    Column("paper_order_leg_id", String(36), primary_key=True),
    Column(
        "paper_order_id",
        String(36),
        ForeignKey("paper_orders.paper_order_id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    ),
    Column("leg_role", String(32), nullable=False, index=True),
    Column("client_order_id", String(48), nullable=True, unique=True),
    Column("broker_order_id", String(80), nullable=True, unique=True),
    Column("parent_broker_order_id", String(80), nullable=True, index=True),
    Column("symbol", String(24), nullable=False, index=True),
    Column("side", String(8), nullable=False),
    Column("order_type", String(24), nullable=False),
    Column("time_in_force", String(16), nullable=False),
    Column("quantity", Numeric(24, 10), nullable=False),
    Column("filled_quantity", Numeric(24, 10), nullable=False),
    Column("filled_average_price", Numeric(20, 8), nullable=True),
    Column("limit_price", Numeric(20, 8), nullable=True),
    Column("stop_price", Numeric(20, 8), nullable=True),
    Column("status", String(40), nullable=False, index=True),
    Column("lifecycle_complete", Boolean, nullable=False),
    Column("submission_attempts", Integer, nullable=False),
    Column("broker_payload_json", JSON, nullable=False),
    Column("error_code", String(120), nullable=True),
    Column("error_message", Text, nullable=True),
    Column("submitted_at", DateTime(timezone=True), nullable=True),
    Column("last_reconciled_at", DateTime(timezone=True), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False, index=True),
    UniqueConstraint(
        "paper_order_id",
        "leg_role",
        name="uq_paper_order_legs_order_role",
    ),
)

paper_order_events = Table(
    "paper_order_events",
    metadata,
    Column("paper_order_event_id", String(36), primary_key=True),
    Column(
        "paper_order_id",
        String(36),
        ForeignKey("paper_orders.paper_order_id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    ),
    Column("sequence", Integer, nullable=False),
    Column("broker_status", String(40), nullable=False, index=True),
    Column("filled_quantity", Numeric(24, 10), nullable=False),
    Column("filled_average_price", Numeric(20, 8), nullable=True),
    Column("lifecycle_complete", Boolean, nullable=False),
    Column("payload_json", JSON, nullable=False),
    Column("observed_at", DateTime(timezone=True), nullable=False, index=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint(
        "paper_order_id",
        "sequence",
        name="uq_paper_order_events_order_sequence",
    ),
)

paper_account_snapshots = Table(
    "paper_account_snapshots",
    metadata,
    Column("paper_account_snapshot_id", String(36), primary_key=True),
    Column("broker_account_id", String(80), nullable=False, index=True),
    Column("status", String(32), nullable=False),
    Column("currency", String(8), nullable=False),
    Column("cash", Numeric(24, 8), nullable=False),
    Column("buying_power", Numeric(24, 8), nullable=False),
    Column("equity", Numeric(24, 8), nullable=False),
    Column("portfolio_value", Numeric(24, 8), nullable=False),
    Column("last_equity", Numeric(24, 8), nullable=False),
    Column("pattern_day_trader", Boolean, nullable=False),
    Column("trading_blocked", Boolean, nullable=False),
    Column("transfers_blocked", Boolean, nullable=False),
    Column("account_blocked", Boolean, nullable=False),
    Column("payload_json", JSON, nullable=False),
    Column("observed_at", DateTime(timezone=True), nullable=False, index=True),
)

paper_position_snapshots = Table(
    "paper_position_snapshots",
    metadata,
    Column("paper_position_snapshot_id", String(36), primary_key=True),
    Column(
        "paper_account_snapshot_id",
        String(36),
        ForeignKey(
            "paper_account_snapshots.paper_account_snapshot_id",
            ondelete="CASCADE",
        ),
        nullable=False,
        index=True,
    ),
    Column("symbol", String(24), nullable=False, index=True),
    Column("side", String(8), nullable=False),
    Column("quantity", Numeric(24, 10), nullable=False),
    Column("average_entry_price", Numeric(20, 8), nullable=False),
    Column("current_price", Numeric(20, 8), nullable=False),
    Column("market_value", Numeric(24, 8), nullable=False),
    Column("cost_basis", Numeric(24, 8), nullable=False),
    Column("unrealized_pnl", Numeric(24, 8), nullable=False),
    Column("unrealized_pnl_fraction", Numeric(20, 10), nullable=False),
    Column("payload_json", JSON, nullable=False),
    Column("observed_at", DateTime(timezone=True), nullable=False, index=True),
    UniqueConstraint(
        "paper_account_snapshot_id",
        "symbol",
        name="uq_paper_position_snapshots_account_symbol",
    ),
)

paper_runs = Table(
    "paper_runs",
    metadata,
    Column("paper_run_id", String(36), primary_key=True),
    Column("trigger", String(80), nullable=False),
    Column("status", String(24), nullable=False, index=True),
    Column("enrollment_count", Integer, nullable=False),
    Column("orders_submitted", Integer, nullable=False),
    Column("orders_reconciled", Integer, nullable=False),
    Column("started_at", DateTime(timezone=True), nullable=False),
    Column("finished_at", DateTime(timezone=True), nullable=False, index=True),
    Column("error_code", String(120), nullable=True),
    Column("detail_json", JSON, nullable=False),
)

runtime_controls = Table(
    "runtime_controls",
    metadata,
    Column("control_key", String(80), primary_key=True),
    Column("state_json", JSON, nullable=False),
    Column("updated_by", String(80), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

runtime_leases = Table(
    "runtime_leases",
    metadata,
    Column("lease_key", String(80), primary_key=True),
    Column("lease_owner", String(120), nullable=False, index=True),
    Column("lease_token", String(36), nullable=False, unique=True),
    Column("lease_expires_at", DateTime(timezone=True), nullable=False, index=True),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

code_change_sessions = Table(
    "code_change_sessions",
    metadata,
    Column("code_change_session_id", String(36), primary_key=True),
    Column("status", String(32), nullable=False, index=True),
    Column("request", Text, nullable=False),
    Column("scope_json", JSON, nullable=False),
    Column("base_git_sha", String(64), nullable=False),
    Column("branch_name", String(160), nullable=False),
    Column("worktree_path", Text, nullable=True),
    Column("diff_sha256", String(64), nullable=True),
    Column("diff_text", Text, nullable=True),
    Column("tests_json", JSON, nullable=False),
    Column("proposed_commit_subject", String(240), nullable=True),
    Column("committed_git_sha", String(64), nullable=True),
    Column("requested_by", String(80), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False, index=True),
    Column("approved_at", DateTime(timezone=True), nullable=True),
)
